spring.application.name=file_Rouge

# Nom d'utilisateur de la base de données
server.port=9090
# URL de connexion à la base de données H2
spring.datasource.url=jdbc:h2:mem:testdb

# Nom d'utilisateur de la base de données
spring.datasource.username=user

# Mot de passe de la base de données
spring.datasource.password=

# Driver JDBC
spring.datasource.driver-class-name=org.h2.Driver

# Mode H2 console (facultatif pour voir les données via le navigateur)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Dialecte JPA pour H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Montrer les requêtes SQL dans la console (facultatif)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Stratégie de génération du schéma de la base de données
spring.jpa.hibernate.ddl-auto=update

spring.mvc.contentnegotiation.favor-path-extension=false
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.media-types.json=application/json
spring.mvc.contentnegotiation.default-content-type=application/json
